autoload -U compinit
compinit

#autoload perldoc
#autoload predict-on
#predict-on
setopt auto_cd
setopt auto_pushd
setopt correct
setopt list_packed

setopt nolistbeep
setopt no_beep

HISTFILE=~/.zsh_history
HISTSIZE=100000
SAVEHIST=100000
setopt hist_ignore_dups     # ignore duplication command history list
setopt share_history        # share command history data

autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^P" history-beginning-search-backward-end
bindkey "^N" history-beginning-search-forward-end

# > for users
# # for root
if [ $(id -u) -eq 0 ]; then
	PROMPT="
[%?] %F{red}%n%f@%F{green}%m%f:%~ (%T %w)
# "
else
	PROMPT="
[%?] %F{blue}%n%f@%F{green}%m%f:%~ (%T %w)
$ "

fi

case "${TERM}" in
kterm*|xterm*)
    precmd() {
        echo -ne "\033]0;${USER}@${HOST}\007"
    }
    ;;
esac 

if [ "$SSH_AUTH_SOCK" = "" ]; then
	echo -n "ssh-agent: "
	source ~/.ssh-agent-info
	ssh-add -l >&/dev/null

	if [ $? -eq 2 ] ; then
		echo -n "ssh-agent: restart...."
		ssh-agent >~/.ssh-agent-info
		source ~/.ssh-agent-info
	fi
	if ssh-add -l >&/dev/null ; then
		echo "ssh-agent: Identity is already stored."
	else
		ssh-add
		if [ -d ~/.ssh/private_keys ]; then
			for i in $(ls ~/.ssh/private_keys)
			do
				ssh-add ~/.ssh/private_keys/$i
			done
		fi
	fi
fi

systemname=$(uname -s)

#PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/sbin
if [ -d $HOME/.rbenv ]; then
	PATH=$HOME/.rbenv/bin:$PATH
	eval "$(rbenv init -)"
fi
if [ -d "$HOME/.nodebrew/current/bin" ]; then
	export PATH=$HOME/.nodebrew/current/bin:${PATH}
fi
if [ "$(uname)" = "Darwin" ]; then
	if which pyenv > /dev/null; then 
		export CFLAGS="-I$(xcrun --show-sdk-path)/usr/include"
		export PYENV_ROOT="${HOME}/.pyenv" 
		export PATH=${PYENV_ROOT}/shims:${PATH} 
		eval "$(pyenv init -)"; 
	fi
else	
	if [ -f "$HOME/.pyenv/bin/pyenv" ]; then
		export PYENV_ROOT="${HOME}/.pyenv" 
		export PATH=${PYENV_ROOT}/bin:$PATH
		eval "$(pyenv init -)"; 
	fi
fi
if [ -f "$HOME/.nvm/nvm.sh" ]; then
	source "$HOME/.nvm/nvm.sh"
fi

EDITOR=vim
export PATH EDITOR

# Common aliases
if [ "$systemname" = "Darwin" -o "$systemname" = "FreeBSD" ]; then
    alias ls='ls -FG'
else
    alias ls='ls -F --color=auto'
fi

alias l='ls'
alias ll='ls -l'
alias lll='ls -la'
alias mv='mv -i'
alias cp='cp -i'
alias rm='rm -i'
alias now="date '+%Y%m%d%H%M%S'"
alias day="date '+%Y%m%d'"

if [ -f ~/.zshrc_local ]; then
        . ~/.zshrc_local
fi

if [ -f ~/.alias ]; then
        . ~/.alias
fi


